### ISSUE TITLE
Coc-metals doesn't start after update

### ISSUE THREAD

**Issue by jqno** [scalameta/coc-metals#255] opened 2020-07-13 12:15 UTC
**Describe the bug**

After updating coc-metals in Vim, Metals no longer starts. For instance, when I run `:CocList sources`, metals does no longer appear in that list.

**To Reproduce** Steps to reproduce the behavior:

I use Vim-Plug to manage CoC modules. Relevant piece of `.vimrc`:

```
" CoC plugins
Plug 'neoclide/coc.nvim', { 'branch': 'release', 'do': './install.sh',
    \ 'for': ['java', 'javascript', 'json', 'rust', 'scala', 'typescript'] }
Plug 'scalameta/coc-metals', { 'do': 'yarn install --frozen-lockfile' }
" Elided all the other coc-modules such as coc-java, coc-json, etc
```

I issued a `:PlugUpdate coc-metals` command, and it installed successfully. Relevant piece of diff in my `plugin.lock.vim` file:

```
-silent! let g:plugs['coc-metals'].commit = '39ffb0e'
+silent! let g:plugs['coc-metals'].commit = '630450a'
```

(I.e., it updated from the commit hash in the first line to the one in the second line.)

Metals now doesn't start anymore when I open a Scala file.

When I run `CocOpenLog`, I get the following output:

```
2020-07-13T14:03:25.139 ERROR (pid:48141) [extensions] - Error on createExtension coc-metals from /Users/jqno/.vim/plugged/coc-metals/lib/index.js Error: No valid exports main found for '/Users/jqno/dotfiles/vim/plugged/coc-metals/node_modules/promisify-child-process'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at req (/Users/jqno/dotfiles/vim/plugged/coc.nvim/build/index.js:54054:21)
    at Object.<anonymous> (/Users/jqno/dotfiles/vim/plugged/coc-metals/node_modules/metals-languageclient/lib/fetchMetals.js:4:35)
    at Module._compile (/Users/jqno/dotfiles/vim/plugged/coc.nvim/build/index.js:54075:32) {
  code: 'MODULE_NOT_FOUND'
}
2020-07-13T14:03:25.143 INFO (pid:48141) [plugin] - coc.nvim 0.0.78-449dcad0b2 initialized with node: v13.4.0 after 1090ms
```

**Expected behavior**

Coc-metals running as before, except now with more cool features ;)

**Installation:**

- Operating system: macOS Catalina 10.15.5
- Vim or nvim version: Vim 8.1.2400
- coc.nvim version:  0.0.78-449dcad0b2
- coc-metals extension version: Whatever version exists at commit index `630450a` :)
- Metals version: not sure how to find that out (`:CocConfig` to open settings)

**Additional context**

Coc-metals is awesome and I love it. Thank you for making it.

**Comment by ckipp01** [comment] 2020-07-13 13:40
Thanks for reporting @jqno.

I'm unable to actually get this to happen, but I also had someone mention it a bit ago on Gitter. There was also a lot of changes between the two commits that you mention.

If you do a `:CocConfig`, what do you have listed as your `metals.serverVersions`? I also pushed up some new changes this morning, so try updating again to see if that changes anything.

**Comment by jqno** [comment] 2020-07-13 14:01
The update didn't help, unfortunately.

When I do `:CocConfig`, I get my CoC configuration file, which contains the following things, but doesn't have an explicit `metals.serverVersion`:

```
{
  "diagnostic.displayByAle": true,
  "coc.preferences.extensionUpdateCheck": "never",
  "suggest.autoTrigger": "trigger",
  "suggest.noselect": false,
  "snippets.priority": 100,
  "metals.statusBarEnabled": true
}
```

**Comment by ckipp01** [comment] 2020-07-13 14:42
I'm sort of at a loss here at what's going on. By chance are you able to try this with Node lts?

**Comment by jqno** [comment] 2020-07-13 14:51
I'm not sure what that is, but I can maybe try it tonight or tomorrow.

I can also maybe try to narrow down a bit more at which commit the issue started appearing, but that could take some time :)

**Comment by ckipp01** [comment] 2020-07-13 15:02
> I'm not sure what that is, but I can maybe try it tonight or tomorrow.

Ah, sorry I should have been more descriptive. I mean try with the lts version of Node, which is 12.18.2. I see that you're using 13.4 and I've seen some stuff listed online that is _a bit_ similar to what is happening here and the issue was fixed when the update or went back to lts. So I'm curious if that is the issue. I've been able to try this with the latest Node 13 and installation the same way you have listed here without issue. So any way you could narrow would greatly help.

**Comment by glottologist** [comment] 2020-07-13 15:43
I get the same issue using node 12.  
```
[coc.nvim]: UnhandledRejection: spawn ENOTDIR                                                                                                                                                                                        
Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at Object.spawn (child_process.js:548:9)
    at Object.spawn (/home/jason/.config/coc/extensions/node_modules/coc-metals/node_modules/promisify-child-process/index.cjs:134:46)
    at Object.fetchMetals (/home/jason/.config/coc/extensions/node_modules/coc-metals/node_modules/metals-languageclient/lib/fetchMetals.js:7:38)
    at y (/home/jason/.config/coc/extensions/node_modules/coc-metals/lib/index.js:28:2613)
    at /home/jason/.config/coc/extensions/node_modules/coc-metals/lib/index.js:28:1656
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

My CocInfo ;
```
## versions
vim version: NVIM v0.4.3
node version: v12.18.2
coc.nvim version: 0.0.78-449dcad0b2
coc.nvim directory: /home/jason/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux
```

**Comment by jqno** [comment] 2020-07-13 17:15
I switched to node 12.18.2. Now I do see some things happening. I see it downloading Metals 0.9.1 (not sure if it succeeds, the message flashed briefly and was gone) and it also asked me to re-import my build. In the end, though, coc-metals does not start properly: I get no completions and metals doesn't appear in `:CocList sources`, for instance. `:CocOpenLog` gives me this:

```
2020-07-13T19:12:33.449 INFO (pid:72382) [plugin] - coc.nvim 0.0.78-449dcad0b2 initialized with node: v12.18.2 after 475ms
2020-07-13T19:12:36.847 INFO (pid:72382) [language-client-index] - Language server "metals" started with 72422
2020-07-13T19:12:38.379 ERROR (pid:72382) [server] - unhandledRejection  Promise {
  <rejected> TypeError: Cannot read property 'treeViewProvider' of undefined
      at r.initialize (/Users/jqno/dotfiles/vim/plugged/coc-metals/lib/index.js:22:856)
      at LanguageClient.initializeFeatures (/Users/jqno/dotfiles/vim/plugged/coc.nvim/build/index.js:60514:21)
      at /Users/jqno/dotfiles/vim/plugged/coc.nvim/build/index.js:60178:18
} TypeError: Cannot read property 'treeViewProvider' of undefined
    at r.initialize (/Users/jqno/dotfiles/vim/plugged/coc-metals/lib/index.js:22:856)
    at LanguageClient.initializeFeatures (/Users/jqno/dotfiles/vim/plugged/coc.nvim/build/index.js:60514:21)
    at /Users/jqno/dotfiles/vim/plugged/coc.nvim/build/index.js:60178:18
```

**Comment by ckipp01** [comment] 2020-07-13 17:47
> I switched to node 12.18.2, and back to commit 7ecd7df of coc-metals. Now I do see some things happening. I see it downloading Metals 0.9.1 (not sure if it succeeds, the message flashed briefly and was gone) and it also asked me to re-import my build. In the end, though, coc-metals does not start properly: I get no completions and metals doesn't appear in :CocList sources, for instance. :CocOpenLog gives me this:

🤔 so the order seems a bit off here. If the download flashed and then went away followed by prompting you to re-import, then Metals for sure started, which is a good thing. That also makes debugging much easier. Are you able to create the [`lsp.trace.json`](https://scalameta.org/metals/docs/contributors/getting-started.html#json-rpc-trace) file that we mention here, open a project until you get the error, close it, and then send me the logs?

**Comment by jqno** [comment] 2020-07-13 17:56
So, I decided to git-bisect my way through the coc-metals history to figure out at which commit the error occurred, and I ended up at the most recent commit (`7ecd7df`) with things still working correctly. Which means that my problem is now solved, I guess, but in the most unsatisfying way :). Perhaps one of the smaller upgrade steps modified some obscure but necessary piece of global state somewhere, that the larger upgrade step simply didn't? If so, then a clean install of coc-metals should probably make the issue reproducible as well?

**Comment by ckipp01** [comment] 2020-07-13 18:12
Unsatisfying indeed. I'm glad you got it working, but it still bugs me seeing that @glottologist also has the issue.

> then a clean install of coc-metals should probably make the issue reproducible as well?

You would think yes, but I'm unable to mimic if after whipping my environment and installing via vim plug or coc.nvim. The latest error you should was also a bit odd since there shouldn't have been a way for the prompt to happen before the error with the `treeViewProvider` being read from undefined. Plus currently, we don't read `treeViewProvider` anywhere, only set it in `initializationOptions`.

**Comment by jqno** [comment] 2020-07-13 18:17
Could it also have something to do with the fact that I'm one of those stubborn people who wants to manage plugin versions by hand, instead of just issuing a `:CocInstall coc-metals` and letting CoC manage the updates? Does @glottologist do that too?

**Comment by ckipp01** [comment] 2020-07-13 18:19
Honestly, you're not stubborn, `:CocInstall coc-metals` is a nightmare, so you're wise to not use it. The creator of coc.nvim doesn't even recommend people to use it. So it shouldn't be the fact that you manage it by hand that is causing any issues.

**Comment by jqno** [comment] 2020-07-13 18:25
Haha, wow, I didn't know it was that bad.

Well, since I can't reproduce this issue anymore myself, I'm not sure how I can be of further help in solving it. If any new evidence comes up, I'll be happy to try it out.

**Comment by ckipp01** [comment] 2020-07-13 18:32
To be fair, the `:CocInstall coc-metals` isn't the _worst_, but I've had all sort of problems with the `:CocInstall https://github.com/scalameta/coc-metals`. I recommend to keep updating the way you do.

I'll going to keep this open to see if I can gather any more info on this as I try a few more things, and also see if we can get @glottologist to get his issue solved as well.

**Comment by glottologist** [comment] 2020-07-13 19:10
I have tried ``` :CocInstall coc-metals``` and using vim-plug but it didn't make a difference

**Comment by glottologist** [comment] 2020-07-15 13:05
When I update my plugin I do get this error:
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.

**Comment by ckipp01** [comment] 2020-07-15 18:22
So after it's excluded, it should still be installed correctly I'm assuming? Are you still hitting on the same problem you mentioned above?

**Comment by glottologist** [comment] 2020-07-15 19:39
No I still hit the same problem.  I am going to try it on a different flavour of linux to see if I get the same issue

**Comment by ckipp01** [comment] 2020-07-15 19:51
What distro are you running? I just tried a fresh install on my Ubuntu machine without any issues and I also test against Ubuntu, so that shouldn't be an issue. There also isn't a lot that I can think of that the Distro _should_ affect for this.

**Comment by glottologist** [comment] 2020-07-16 11:42
I am on Manjaro.  I will try on a fresh Ubuntu or Fedora and see if I still get the issue.

**Comment by mmako1** [comment] 2020-07-21 02:35
I was running into the same problem here , but running  `:CocInstall coc-metals` fixed the issue. I initially tried re-running `:CocUpdate`, but it did nothing to resolve the issue.  Running `:CocDiagnostics` was also returning no errors, so I'm quite unsure as to what the cause is.

**System Information** 

Kernel: Linux 5.7.9-arch1-1
vim version: NVIM v0.4.3
coc.nvim version: 0.0.78

**Comment by z2oh** [comment] 2020-09-25 17:46
Running into the same issue as @glottologist on OS X.

The error message printed in neovim is as follows:
```
[coc.nvim]: UnhandledRejection: spawn ENOTDIR
Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:402:11)
    at Object.spawn (child_process.js:553:9)
    at Object.spawn (/Users/jaday/.config/coc/extensions/node_modules/coc-metals/node_modules/promisify-child-process/index.cjs:134:46)
    at Object.fetchMetals (/Users/jaday/.config/coc/extensions/node_modules/coc-metals/node_modules/metals-languageclient/lib/fetchMetals.js:7:38)
    at k (/Users/jaday/.config/coc/extensions/node_modules/coc-metals/lib/index.js:28:2623)
    at /Users/jaday/.config/coc/extensions/node_modules/coc-metals/lib/index.js:28:1666
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
Looks like the issue is showing up here:
```
    return promisify_child_process_1.spawn(javaPath, [
        ...javaOptions,
        ...fetchProperties,
        "-Dfile.encoding=UTF-8",
        "-jar",
        coursierPath,
        "fetch",
        "-p",
        "--ttl",
        // Use infinite ttl to avoid redunant "Checking..." logs when using SNAPSHOT
        // versions. Metals SNAPSHOT releases are effectively immutable since we
        // never publish the same version twice.
        "Inf",
        `org.scalameta:metals_2.12:${serverVersion}`,
        "-r",
        "bintray:scalacenter/releases",
        "-r",
        "sonatype:public",
        "-r",
        "sonatype:snapshots",
        "-p",
    ]
```
Which leads me to believe I am supposed to have something installed that I don't. I installed OpenJDK 11 via `brew`. Running `java -version` prints:
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

I have `scala` installed via `brew` as well.

I'm relatively unfamiliar with the Java ecosystem, so I might be missing something obvious. Sorry if none of this information is particularly useful.

**Comment by ckipp01** [comment] 2020-09-26 16:31
Thanks for the report @z2oh. Is this issue on the first install or after the recent update? How are you installing, via `:CocInstall` or adding into to Vim Plug or something similiar?

Also, what version of Node are you using?

**Comment by z2oh** [comment] 2020-10-07 22:25
Sorry for the late response. This issue is on the first install - I have never been able to get this to work. I've tried both `:CocInstall` and `vim-plug` with the same result.

When I run `node --version` I get `v14.12.0`. I'm not too familiar with the node ecosystem, so I hope this is the data you were asking for.

**Comment by ckipp01** [comment] 2020-10-09 09:42
One thing you can try is to explicitly set your java home in `metals.javaHome`. It could be the command is failing to launch coursier because it doesn't have reference to your jdk. Are you able to explicitly set that and give it another try?

**Comment by z2oh** [comment] 2020-10-09 17:34
I went to set my `metals.javaHome` and found I already had set it, presumably to the wrong thing. When I removed that, everything worked! I must've tried to set it explicitly to debug an earlier issue and then forgot about it. Thanks for your help.

**Comment by ckipp01** [comment] 2020-10-09 20:29
Great, glad you were able to get it working @z2oh!

Since I'm unsure of the status of the other issues that were listing in here (seemingly most seem to have been solved), I'm going to close this. If someone still does have an issue, feel free to open another issue.

**Closed by ckipp01** 2020-10-09 20:29 UTC
Labels: bug, unable to reproduce

**Comment by yazgoo** [comment] 2020-11-19 09:41
Got the exact same error as mentionned at the top of this issue today.

Was using node version `v13.6.0`

Upgrading to `v15.2.1` by running `nvm install node --reinstall-packages-from=node` fixed it for me.
