### ISSUE TITLE
Should code-actions work?

### ISSUE THREAD

**Issue by BonaBeavis** [scalameta/coc-metals#19] opened 2020-01-09 19:12 UTC
I dont know if I have a configuration error, should code actions like "Import Foo" work?

**Comment by ckipp01** [comment] 2020-01-09 21:59
In theory, yes, they should be working. Are you getting any specific errors?

I just tested it locally, and I am able to get them working, however, the behavior isn't quite acting as expecting.

![2020-01-09 22 53 51](https://user-images.githubusercontent.com/13974112/72108222-617aae00-3333-11ea-87e4-01f38785613d.gif)

For example, I was able to trigger it with `<leader>a l` which was the direction of the diagnostic, but I also believe that `<leader>ac` should have triggered this. Let me look into this a bit and figure out if it's an issue with coc-metals, coc.nvim, or metals.

**Comment by BonaBeavis** [comment] 2020-01-10 13:15
No errors, it just shows code actions from coc-snippets. I also have coc-java installed and there the code actions work. And if I remember correctly they also worked with metals added manually to CocConfig. So I would guess the issue is somewhere in coc-metals.

**Comment by ckipp01** [comment] 2020-01-11 12:17
> And if I remember correctly they also worked with metals added manually to CocConfig. So I would guess the issue is somewhere in coc-metals.

So I was just tested this without `coc-metals` and just manually adding metals to my `CocConfig`. The issue is the same, without seeing any available actions. So it's for sure not an issue with the extension itself, which is what I figured since we don't do anything special in the extension for code actions.

I also tested this on Vim 8.2 instead of Neovim, which was actually a worse experience and just hung there. I actually experienced this before, which you can see here https://github.com/neoclide/coc.nvim/issues/1404, but it worked after... and now doesn't again.

Something is for sure going wrong since the code actions work flawlessly in `coc.nvim` when I use them for typescript. I'll keep diving in to see what the deal is.

**Comment by gabro** [comment] 2020-01-11 13:43
We might be filtering the code actions a bit too aggressively on the server. I would check the bit where we filter the diagnostics by their range

**Comment by ckipp01** [comment] 2020-01-11 14:02
Alright, I finally got this figured out.

When you issue a `CocAction`, it will send in the entire line to find any available code actions. The way that we are filtering like @gabro just mentioned won't catch this because we ensure that the diagnostic range encloses the code actions range. Since it's the whole line, going into the next line, this correctly returns `null`. What may want to change that in the future on the Metals side to enable getting any actions on a line?

_However_, there is a nice way to get this to work with `coc.nvim`. In the recommended mappings you'll see the following:

```vim
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
```
Thill will allow you to select where the diagnostic is, and then issue a `<leader>a`, which will correctly send in the correct context that Metals needs, and returns the expected code action. Here is a gif of this working.

![code-action-working](https://user-images.githubusercontent.com/13974112/72205445-533ba780-3483-11ea-89bf-368bf6f98866.gif)

**Comment by ckipp01** [comment] 2020-01-11 14:05
Since this is indeed working in `coc-metals`, I'm going to go ahead and close this here. I'll again link it from the other ticket in main Metals repo https://github.com/scalameta/metals/issues/1283, and you can following the discussion there regarding whether we change the way we filter it in Metals.

**Closed by ckipp01** 2020-01-11 14:05 UTC
Labels: bug
